### ISSUE TITLE
doctable1 needs to better handle schema checking

### ISSUE THREAD

**Issue by devincornell** [devincornell/doctable#12]
Not sure if this will be helpful, but this was an error from Andrei trying to run our analysis.

Traceback (most recent call last):
  File "C:\dvl\hugedw\hdw_main_runner.py", line 41, in <module>
    mes = HDwBootedMultiEmbedding.loadBootedDecadeRangeDb(1940,2000, everyNYears = 5, dbpath = dbpath, bootstrapIndexes = range(0,40))
  File ".\hdw_bootstacks.py", line 150, in loadBootedDecadeRangeDb
    dbpath = dbpath, bootstrapIndex = i)
  File ".\hdw_multiembedding.py", line 184, in loadDecadeRangeDb
    **kwargs) for yr in years}
  File ".\hdw_multiembedding.py", line 184, in <dictcomp>
    **kwargs) for yr in years}
  File ".\hdw_embedding.py", line 43, in loadYearDb
    bmdb = BootModelDB(dbpath)
  File ".\boot_model_db.py", line 33, in _init_
    'UNIQUE(start_year,end_year,bsid,stackid)',
  File "../doctable\doctable\doctable.py", line 34, in _init_
    self._check_schema()
  File "../doctable\doctable\doctable.py", line 64, in _check_schema
    raise Exception(estr.format(cname, ctype, exist_type))
Exception: provided "config" column type "BLOB" does not match existing data schema type "blob".

**Comment by devincornell** [comment]
I handled this by allowing user to turn schema checking off.
