### ISSUE TITLE
When closing database (naturally at end of program or in case of an exception), throws error "Cannot operate on a closed database."

### ISSUE THREAD

**Issue by devincornell** [devincornell/doctable#21]
Traceback (most recent call last):
  File "C:\Users\Devin\Python37\lib\site-packages\sqlalchemy\pool\base.py", line 697, in _finalize_fairy
    fairy._reset(pool)
  File "C:\Users\Devin\Python37\lib\site-packages\sqlalchemy\pool\base.py", line 893, in _reset
    pool._dialect.do_rollback(self)
  File "C:\Users\Devin\Python37\lib\site-packages\sqlalchemy\engine\default.py", line 543, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: Cannot operate on a closed database.

**Comment by devincornell** [comment]
This turns out to be pretty weird. I think it has to do with garbage collection order....

**Comment by devincornell** [comment]
I think the issue is that when I call engine.dispose(), the engine replaces it's old connection pool with a new empty one, but the problem is that the DocTable instance still maintains a connection to the old pool, so it is not garbage collected. I think my goal should be to close out connections in the pool before disposing the pool. See this page for more info:
https://docs.sqlalchemy.org/en/14/core/connections.html

This is a relevant paragraph:
`Connections that are checked out are not discarded when the engine is disposed or garbage collected, as these connections are still strongly referenced elsewhere by the application. However, after Engine.dispose() is called, those connections are no longer associated with that Engine; when they are closed, they will be returned to their now-orphaned connection pool which will ultimately be garbage collected, once all connections which refer to it are also no longer referenced anywhere. Since this process is not easy to control, it is strongly recommended that Engine.dispose() is called only after all checked out connections are checked in or otherwise de-associated from their pool.`

**Comment by devincornell** [comment]
Solved by removing all destructor code in doctable and connectengine. I have no idea why this works and it makes me concerned, but nevertheless I'll keep this for now.
