### ISSUE TITLE
doctable2 fails when setting persistent_conn=True

### ISSUE THREAD

**Issue by devincornell** [devincornell/doctable#4]

**Comment by devincornell** [comment]
Did I actually mean persistent_conn=False?

**Comment by devincornell** [comment]
Closing because I can't reproduce the error and furthermore couldn't think of use case for persistent_conn=False. I just finished creating concurrency example and in that case the timeout is more important.

In the original DocTable, a .get() (comparable to .select()) call would yield results instead of return a list meaning, persistent_conn would need to be False to call an .update() inside a .get() loop (where the connection remains open as long as it is looping). I changed that functionality in .select() because I read that the database engine will load results into memory anyways, and thus the list will be returned on a .select() method before the for loop begins.

**Comment by devincornell** [comment]
Traceback (most recent call last):
  File "schema.py", line 50, in <module>
    print(md)
  File "../doctable/doctable2.py", line 113, in __str__
    return '<DocTable2::{} ct: {}>'.format(self._tabname, self.count())
  File "../doctable/doctable2.py", line 221, in count
    ct = self.select_first(cter, where=where, whrstr=whrstr, **kwargs)
  File "../doctable/doctable2.py", line 354, in select_first
    result = self.select(*args, limit=1, **kwargs)
  File "../doctable/doctable2.py", line 437, in select
    return [row[0] for row in result]
  File "../doctable/doctable2.py", line 437, in <listcomp>
    return [row[0] for row in result]
  File "/home/utopia3/dc326/local/anaconda3/lib/python3.6/site-packages/sqlalchemy/engine/result.py", line 944, in __iter__
    row = self.fetchone()
  File "/home/utopia3/dc326/local/anaconda3/lib/python3.6/site-packages/sqlalchemy/engine/result.py", line 1274, in fetchone
    e, None, None, self.cursor, self.context
  File "/home/utopia3/dc326/local/anaconda3/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1473, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/home/utopia3/dc326/local/anaconda3/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/utopia3/dc326/local/anaconda3/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/home/utopia3/dc326/local/anaconda3/lib/python3.6/site-packages/sqlalchemy/engine/result.py", line 1266, in fetchone
    row = self._fetchone_impl()
  File "/home/utopia3/dc326/local/anaconda3/lib/python3.6/site-packages/sqlalchemy/engine/result.py", line 1146, in _fetchone_impl
    return self.cursor.fetchone()
sqlalchemy.exc.ProgrammingError: (sqlite3.ProgrammingError) Cannot operate on a closed database.
(Background on this error at: http://sqlalche.me/e/f405)

**Comment by devincornell** [comment]
I don't think this is relevant anymore.
