### ISSUE TITLE
error when using .select_chunk()

### ISSUE THREAD

**Issue by devincornell** [devincornell/doctable#6]
This is most likely due to not updating the max_rows parameter before this line. Need to update that.

Error message:
Traceback (most recent call last):
  File "make_ppmi.py", line 93, in <module>
    for id,corpus,voc_all in mdb.select_chunk(['id','cooc','vocab'],where=whr):
  File "/home/utopia3/dc326/local/anaconda3/lib/python3.6/site-packages/doctable/doctable2.py", line 474, in select_chunk
    for row in rows[:max_rows-offset]:
TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'

**Comment by devincornell** [comment]
I think I fixed this. No recent issues.
